platform :ios, '9.0'

target 'DouyinOpenSDKDemo' do
  pod 'DouyinOpenSDK'
  pod 'BDTDebugBox', :path => 'LocalSpecs/BDTDebugBox'
  pod 'QBImagePickerController'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
